/*
Contient tous les termes lisibles par l'utilisateur
Dans l'objet "fr" on met les termes français
Dans l'objet "en" on met les termes anglais
Dans la constante STRING_OPTIONS on met les clés associées dans les objets "fr" et "en"
*/
import * as Localization from "expo-localization";
import i18n from "i18n-js";
// Set the key-value pairs for the different languages you want to support.
i18n.translations = {
  fr: {
    email: "Adresse courriel",
    password: "Mot de passe",
    login: "Connexion",
    zone: "Zone",
    see: "Voir",
    map: "Carte",
    maps: "Cartes",
    area: "Région",
    trails: "Sentiers",
    points_of_interests: "Points d'intérêts",
    service: "Service",
    summit: "Sommet",
    view: "Vue",
    nature: "Nature",
    parking: "Stationnement",
    restroom: "Toilettes",
    camping: "Camping",
    telephone: "Téléphone",
    picnic: "Picnic",
    refuge: "Refuge",
    hosting: "Hébergement",
    unknown: "Inconnu",
    type: "Type",
    description: "Description",
    coordinates: "Coordonnées",
    latitude: "Latitude",
    longitude: "Longitude",
    altitude: "Altitude",
    difficulty: "Difficulté",
    logout: "Se déconnecter",
    referenceNumber: "Numéro de référence",
    codeHelp: "Vous avez le code d'un point d'intérêt?",
    code: "Code",
    search: "Rechercher",
    invalid_code: "Code invalide: veuillez entrer un code valide",
    empty_field: "Champs vide détecté: veuillez remplir tous les champs",
    i_have_a_code: "J'ai un code",
    i_am_member: "Je suis membre",
    login_failed: "Erreur: accès refusé",
    invalid_email_format: "Errur: format de courriel invalide",
    internet_is_required_to_continue:
      "Une connexion internet est requise pour continuer",
    retry: "Réessayer",
    error_occured: "Il y a eu une erreur. Veuillez réessayer.",
    successfully_logout: "Vous vous êtes bien déconnecté",
    partners: "Partenaires",
  },
  en: {
    email: "Email address",
    password: "Password",
    login: "Login",
    zone: "Zone",
    see: "See",
    map: "Map",
    maps: "Maps",
    area: "Area",
    trails: "Trails",
    points_of_interests: "Points of interest",
    service: "Service",
    summit: "Summit",
    view: "View",
    nature: "Nature",
    parking: "Parking",
    restroom: "Restroom",
    camping: "Camping",
    telephone: "Telephone",
    picnic: "Picnic",
    refuge: "Refuge",
    hosting: "Hosting",
    unknown: "Unknown",
    type: "Type",
    description: "Description",
    coordinates: "Coordinates",
    latitude: "Latitude",
    longitude: "Longitude",
    altitude: "Altitude",
    difficulty: "Difficulty",
    logout: "Log out",
    referenceNumber: "Reference number",
    codeHelp: "You have the code of an interest point?",
    code: "Code",
    search: "Search",
    invalid_code: "Invalid code: please enter a valid code",
    empty_field: "Empty field: please fill all fields",
    i_have_a_code: "I have a code",
    i_am_member: "I am a member",
    login_failed: "Error: credentials unknown",
    invalid_email_format: "Error: invalid email format",
    error_occured: "An error occured. Please retry.",
    retry: "Retry",
    successfully_logout: "You successfully logged out",
    partners: "Partners",
  },
};

export const STRINGS_OPTIONS = {
  email: "email",
  password: "password",
  login: "login",
  zone: "zone",
  see: "see",
  map: "map",
  maps: "maps",
  area: "area",
  trails: "trails",
  points_of_interests: "points_of_interests",
  service: "service",
  summit: "summit",
  view: "view",
  nature: "nature",
  parking: "parking",
  restroom: "restroom",
  camping: "camping",
  telephone: "telephone",
  picnic: "picnic",
  refuge: "refuge",
  hosting: "hosting",
  unknown: "unknown",
  type: "type",
  description: "description",
  coordinates: "coordinates",
  latitude: "latitude",
  longitude: "longitude",
  altitude: "altitude",
  difficulty: "difficulty",
  logout: "logout",
  referenceNumber: "referenceNumber",
  codeHelp: "codeHelp",
  code: "code",
  search: "search",
  invalid_code: "invalid_code",
  empty_field: "empty_field",
  i_have_a_code: "i_have_a_code",
  i_am_member: "i_am_member",
  login_failed: "login_failed",
  invalid_email_format: "invalid_email_format",
  error_occured: "error_occured",
  retry: "retry",
  successfully_logout: "successfully_logout",
  partners: "partners",
};

// Récupère le langage de l'appareil de l'utilisateur
i18n.locale = Localization.locale;
i18n.fallbacks = true;

export function getUserLanguage(): string {
  return Localization.locale;
}
